version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yango
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  localstack:
    image: localstack/localstack:2
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - "localstack_data:/var/lib/localstack"

  osrm:
    image: osrm/osrm-backend:latest
    command: osrm-routed --algorithm mld /data/monaco.osrm
    ports:
      - "5000:5000"
    volumes:
      - osrmdata:/data
    # For demo, you need to provide /data/monaco.osrm (or other extract)

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - OSRM_BASE_URL=${OSRM_BASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - SESSION_COOKIE_NAME=${SESSION_COOKIE_NAME}
      - SESSION_COOKIE_DOMAIN=${SESSION_COOKIE_DOMAIN}
      - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE}
      - API_PORT=${API_PORT}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - default

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - NEXT_PUBLIC_API_BASE_PATH=${NEXT_PUBLIC_API_BASE_PATH}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - NEXT_PUBLIC_MAP_STYLE=${NEXT_PUBLIC_MAP_STYLE}
      - WEB_PORT=${WEB_PORT}
    depends_on:
      - api
    networks:
      - default

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - api

volumes:
  pgdata:
  localstack_data:
  osrmdata: